# Generated by Django 5.0.2 on 2024-09-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=50)),
                ('uemail', models.CharField(max_length=50)),
                ('upass', models.CharField(max_length=10)),
            ],
        ),
    ]
