# Generated by Django 5.0.2 on 2024-09-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_new_visiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_new_visiter',
            old_name='Email',
            new_name='email',
        ),
    ]
