# Generated by Django 5.0.2 on 2024-09-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_deparement_add_new_visiter_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_visiter',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='add_new_visiter',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='add_new_visiter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='add_new_visiter',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='add_new_visiter',
            name='phonenum',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_new_visiter',
            name='reasontomeet',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='add_new_visiter',
            name='whomtomeet',
            field=models.CharField(max_length=100),
        ),
    ]
