# Generated by Django 5.0.2 on 2024-09-10 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_add_new_visiter_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_new_visiter',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
