# Generated by Django 5.0.2 on 2024-09-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_add_new_visiter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_new_visiter',
            name='remark',
            field=models.CharField(default='', max_length=20),
        ),
    ]
