# Generated by Django 5.0.2 on 2024-09-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_new_visiter_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_visiter',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
