# Generated by Django 5.0.2 on 2024-09-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_add_new_visiter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_visiter',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
